# Generated by Django 6.0.1 on 2026-01-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Customer',
        ),
    ]
